name: ci

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  CTEST_NO_TESTS_ACTION: error

on:
  push:
    paths:
      - "**.c"
      - "**.cpp"
      - "**/*.f90"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci.yml"

jobs:

  linux_mac:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    env:
      CC: gcc-13
      CXX: g++-13
      FC: gfortran-13

    steps:
    - uses: actions/checkout@v4

    - run: cmake --workflow --preset default


  msvc:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - run: cmake --workflow --preset msvc
